version: '3.9'
volumes:
  sql:
services:
  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./.dcoker/mysql/Dockerfile
    ports:
      - 3308:3306
    volumes:
      - sql:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=sql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo

      # could not find /Users/jam/project/docker/docker-mysql-go-study/.dcoker/.dcoker/mysql: 
      # stat /Users/jam/project/docker/docker-mysql-go-study/.dcoker/.dcoker/mysql: 