version: '3.9'
volumes:
  sql:
services:
  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - 3308:3306
    volumes:
      - sql:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=Asia/Tokyo