@startuml NiziProject
skinparam PackageStyle rectangle

package ユーザー集約 {
  object ユーザー {
    ユーザーID
    名前
    メールアドレス
    パスワード
    スキルID
    自己紹介
    経歴ID

  }

  object スキル {
    スキルID
    タグID
    評価
    年数

  }

  object 経歴 {
    - 詳細
    - 西暦from(始めた時)
    - 西暦to（終了した時）
  }
}

note top of ユーザー
  - 必須項目
    - 名前: 255文字以内(ユニーク)
    - メールアドレス: 255文字以内
    - パスワード: 12文字以上,英数字それぞれ最低1文字以上
    - スキル: 複数
  - 任意項目
    - 自己紹介: 2000字以内
    - 経歴: 複数
end note

note bottom of スキル
  - タグ名(選択式)
  - 評価: 1~5
  - 年数: ０以上のint型(5年まで)
  - 1つ以上は記載
end note

note bottom of 経歴
  - 詳細: 1000字以内
  - 西暦from: 1970年以上のint型
  - 西暦to: 1970年以上のint型、西暦fromよりも大きい数字
end note

ユーザー "1..n" -down-> "1" スキル
ユーザー "1..n" -down-> "1" 経歴

package タグ集約 {
  object タグ {
    タグID
    タグ名(選択式)
  }
}

スキル "1" <-down-> "1" タグ

package メンター募集集約 {
  object メンター募集{
    メンター募集ID
    タイトル
    カテゴリ
    相談形式
    相談方式
    ディスクリプション
    予算(from円~to円)
    応募期間
    ステータス
    タグID(複数OK)
    提案したユーザID
  }

}

package メンター募集提案集約{
  object メンター募集提案 {
    メンター募集提案ID
    メンター募集ID
    提案内容
  }
}

note left of メンター募集
  - 必須項目
    - タイトル: 255文字以内
    - カテゴリ(1つ)
        - プログラミング
        - マーケティング
        - デザイン
        - ライティング
        - 動画・映像
        - ビジネス
        - 語学
        - ライフスタイル
    - 相談形式
        - 単発
        - 継続
    - 相談方式
        - チャット
        - ビデオ通話
    - ディスクリプション(2000文字)
    - 予算(from円~to円)
        - 1000円以上の数値
    - 応募期間
        - 1日単位
        - 最大14日後まで可能
    - ステータス(公開or中止)
- 任意項目
    - タグ(複数OK)
end note

note bottom of メンター募集提案
  - 提案内容: 2000文字以内
  - 提案できるのはスキルを5個以上持つユーザのみ 
end note

メンター募集 "1..n" -down->  メンター募集提案 
メンター募集 "1..n" -down->  タグ 
ユーザー "1..n" -down->  メンター募集

package プラン集約 {
  object プラン {
    プランID
    タイトル
    カテゴリ(1つ)
    タグ(5個まで)
    内容
    ステータス
    相談形式
    金額
    相談方式
    プランを作成したユーザID

  }


}

package プラン契約リクエスト{
  object プラン契約リクエスト {
    プラン契約リクエストID
    メッセージ(最大500文字)
  }
}

package プラン契約承認 {
  object プラン契約承認 {
    プラン契約承認ID
    メッセージ(最大500文字)
  }

}

note right of プラン
  - 必須項目
    - タイトル: 255文字以内
    - カテゴリ(1つ)
        - 上記のカテゴリ参照
    - タグ(5個まで)
        - 選択式
    - 内容
        - 2000文字以内
    - ステータス
        - 公開or中止
        - ステータスが「中止」となっていないものだけ表示する
    - 相談形式
        - 単発
        - 継続
    - 金額
  - 任意項目
      - 相談方式
          - チャットorビデオ電話

  * ページネーション20件
end note

ユーザー "1..n" -down-> プラン
プラン "1..n" -down-> プラン契約リクエスト
プラン "1..n" -down-> プラン契約承認
プラン "1..n" -down-> タグ





@enduml
